-- Trading Assistant V2.6 - Supabase Setup
-- Im Supabase SQL Editor einmal ausführen.

create table if not exists public.assets (
  id bigint generated by default as identity primary key,
  isin text,
  name text not null,
  symbol text,
  exchange text,
  status text default 'Watchlist',
  sort_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.turbos (
  id bigint generated by default as identity primary key,
  isin text not null,
  name text default 'Turbo',
  status text default 'Watchlist',
  underlying text default '',
  sort_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.app_settings (
  id integer primary key,
  settings jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);

-- Diese App verwendet den Supabase Secret Key ausschließlich serverseitig in Streamlit Secrets.
-- Der Secret Key umgeht RLS und darf NIEMALS in GitHub oder im Browsercode stehen.
alter table public.assets enable row level security;
alter table public.turbos enable row level security;
alter table public.app_settings enable row level security;


create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  asset_name text,
  symbol text,
  isin text,
  status text,
  signal_date timestamptz,
  entry_price double precision,
  score integer,
  short_score integer,
  medium_score integer,
  risk_score integer,
  rsi double precision,
  news_sentiment double precision,
  recommendation text,
  price_5d double precision,
  price_10d double precision,
  price_20d double precision,
  perf_5d double precision,
  perf_10d double precision,
  perf_20d double precision,
  created_at timestamptz default now()
);

alter table public.signals enable row level security;


alter table public.assets add column if not exists quantity double precision default 0;
alter table public.assets add column if not exists avg_entry double precision default 0;

alter table public.signals add column if not exists quantity double precision default 0;
alter table public.signals add column if not exists avg_entry double precision default 0;
